language: python
sudo: false
cache:
  directories:
    - eggs
    - bower_components
    - downloads
python:
  - 3.4
install:
  - ln -s development.cfg buildout.cfg
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
after_success:
  - bin/coveralls
