sudo: false
cache:
  directories:
    - eggs
    - bower_components
    - downloads
install:
  - ln -s development.cfg buildout.cfg
  - docker-compose build
  - docker-compose run web python bootstrap.py
  - docker-compose run web bin/buildout
script:
  - docker-compose run web bin/test
after_success:
  - docker-compose run web bin/coveralls
