language: python
python:
  - "3.3"
notifications:
  irc:
    channels: "irc.freenode.org#nens"
    on_success: change
  email: false
install:
  - "ln -s development.cfg buildout.cfg"
  - "python bootstrap.py"
  - "bin/buildout"
script:
  - "bin/django test trs"
after_success:
  - bin/coveralls
