language: python
sudo: false
cache:
  directories:
    - egg
python:
  - "3.3"
install:
  - ln -s development.cfg buildout.cfg
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
after_success:
  - bin/coveralls
