version: '2'

services:

  memcache:
    image: memcached
    restart: unless-stopped

  web:
    build: .
    command: "bin/gunicorn -b 0.0.0.0:${PORT:-5000} --workers=3 --timeout 90 --preload --max-requests=10000 trs.wsgi"
    ports:
      - "5000:5000"
    volumes:
      - ./var:/code/var
    links:
      - memcache
    environment:
      - DJANGO_SETTINGS_MODULE=trs.settings
      # Can be set in .env, we'll pass them on.
      - SECRET_KEY
      - DEBUG
      - SSO_KEY
      - SSO_SECRET
      # TODO: sentry/raven
