version: '2'
services:
  memcache:
    image: memcached

  web:
    build: .
    command: "bin/django runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - memcache
