version: '2'

services:

  memcache:
    image: memcached
    restart: unless-stopped

  web:
    build: .
    command: "bin/gunicorn -b 0.0.0.0:5000 --workers=3 --timeout 90 --preload --max-requests=10000 trs.wsgi"
    ports:
      - "5000:5000"
    volumes:
      - ./var:/code/var
    links:
      - memcache
