version: '2'

services:

  memcache:
    image: memcached
    restart: unless-stopped

  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./var:/code/var
    links:
      - memcache
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=trs.settings
      - MEMCACHE_ADDRESS=memcache:11211
      # Can be set in .env, we'll pass them on.
      - SECRET_KEY
      - DEBUG
      - SENTRY_DSN
      - NENS_AUTH_ISSUER
      - NENS_AUTH_CLIENT_ID
      - NENS_AUTH_CLIENT_SECRET
