version: '2'

services:

  memcache:
    image: memcached
    restart: unless-stopped

  web:
    build: .
    command: "gunicorn -b 0.0.0.0:${PORT:-5000} --workers=3 --timeout 90 --preload --max-requests=10000 trs.wsgi"
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./var:/code/var
    links:
      - memcache
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=trs.settings
      # Can be set in .env, we'll pass them on.
      - SECRET_KEY
      - DEBUG
      - SENTRY_DSN
      - NENS_AUTH_ISSUER
      - NENS_AUTH_CLIENT_ID
      - NENS_AUTH_CLIENT_SECRET
