version: '2'
services:

  web:
    # Run debug webserver.
    command: bin/python manage.py runserver 0.0.0.0:5000
    # Mount the changing directories that change during development.
    volumes:
      - ./requirements/:/code/requirements/
      - ./trs/:/code/trs/
    # TODO: db, index
    # Use the development settings.
    environment:
      # The next is only for during upgrades.
      - PYTHONWARNINGS=always
