# Generated by Django 3.2.16 on 2024-12-17 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0012_remove_project_is_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="mpc",
        ),
    ]
