# Generated by Django 5.2.10 on 2026-01-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0013_remove_person_mpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workassignment',
            name='added',
        ),
        migrations.RemoveField(
            model_name='workassignment',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='workassignment',
            name='year_week',
        ),
    ]
