# Generated by Django 5.2.10 on 2026-01-19 20:56

from django.db import migrations
from django.db.models import Count, Sum


def compress_work_assignments(apps, schema_editor):
    WorkAssignment = apps.get_model("trs", "WorkAssignment")
    # Zap some faulty ones.
    WorkAssignment.objects.filter(assigned_on=None).delete()
    for to_compress in (
        WorkAssignment.objects.all()
        .values("assigned_on", "assigned_to")
        .annotate(Sum("hours"), Sum("hourly_tariff"), Count("id"))
        .filter(id__count__gt=1)
    ):
        # Clean up all existing ones.
        WorkAssignment.objects.filter(
            assigned_on=to_compress["assigned_on"],
            assigned_to=to_compress["assigned_to"],
        ).delete()
        # Create a new one with the totals.
        hours = to_compress["hours__sum"] or 0
        hourly_tariff = to_compress["hourly_tariff__sum"] or 0
        WorkAssignment.objects.create(
            assigned_on_id=to_compress["assigned_on"],
            assigned_to_id=to_compress["assigned_to"],
            hours=hours,
            hourly_tariff=hourly_tariff,
        )
        print(to_compress["assigned_on"], to_compress["assigned_to"])


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0014_remove_workassignment_added_and_more"),
    ]

    operations = [migrations.RunPython(compress_work_assignments)]
