# Generated by Django 5.2.10 on 2026-01-19 21:36

from django.db import migrations, models


def remove_none(apps, schema_editor):
    WorkAssignment = apps.get_model("trs", "WorkAssignment")
    WorkAssignment.objects.filter(hours=None).update(hours=0)
    WorkAssignment.objects.filter(hourly_tariff=None).update(hourly_tariff=0)


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0015_compress_work_assignments"),
    ]

    operations = [
        migrations.RunPython(remove_none),
        migrations.AlterField(
            model_name="workassignment",
            name="hourly_tariff",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="uurtarief"
            ),
        ),
        migrations.AlterField(
            model_name="workassignment",
            name="hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="uren"
            ),
        ),
    ]
