# Generated by Django 5.2.10 on 2026-01-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0016_alter_workassignment_hourly_tariff_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workassignment",
            constraint=models.UniqueConstraint(
                fields=("assigned_on", "assigned_to"), name="unique_work_assignment"
            ),
        ),
    ]
