# Generated by Django 5.2.10 on 2026-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0017_workassignment_unique_work_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="projects", through="trs.WorkAssignment", to="trs.person"
            ),
        ),
    ]
