# Generated by Django 5.2.10 on 2026-01-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0018_project_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="added",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="added_by",
        ),
        migrations.AlterField(
            model_name="booking",
            name="year_week",
            field=models.ForeignKey(
                blank=True,
                help_text="Week waarin geboekt wordt",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trs.yearweek",
                verbose_name="jaar en week",
            ),
        ),
    ]
