# Generated by Django 5.2.10 on 2026-01-20 14:45

from django.db import migrations
from django.db.models import Count, Sum


def compress_bookings(apps, schema_editor):
    Booking = apps.get_model("trs", "Booking")
    for to_compress in (
        Booking.objects.all()
        .values("booked_on", "booked_by", "year_week")
        .annotate(Sum("hours"), Count("id"))
        .filter(id__count__gt=1)
    ):
        # Clean up all existing ones.
        Booking.objects.filter(
            booked_on=to_compress["booked_on"],
            booked_by=to_compress["booked_by"],
            year_week=to_compress["year_week"],
        ).delete()
        # Create a new one with the totals.
        hours = to_compress["hours__sum"] or 0
        Booking.objects.create(
            booked_on_id=to_compress["booked_on"],
            booked_by_id=to_compress["booked_by"],
            year_week_id=to_compress["year_week"],
            hours=hours,
        )
        print(
            to_compress["booked_on"], to_compress["booked_by"], to_compress["year_week"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0019_remove_booking_added_remove_booking_added_by_and_more"),
    ]

    operations = [migrations.RunPython(compress_bookings)]
