# Generated by Django 5.2.10 on 2026-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0020_compress_bookings"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("booked_by", "booked_on", "year_week"), name="unique_booking"
            ),
        ),
    ]
