# Generated by Django 5.2.10 on 2026-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0021_booking_unique_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="uren"
            ),
        ),
    ]
