# Generated by Django 5.2.10 on 2026-01-20 21:24

from django.db import migrations, models


def fix_empty_descriptions(apps, schema_editor):
    ThirdPartyEstimate = apps.get_model("trs", "ThirdPartyEstimate")
    ThirdPartyEstimate.objects.filter(description="").update(
        description="Niet ingevuld"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0022_alter_booking_hours"),
    ]

    operations = [
        migrations.RunPython(fix_empty_descriptions),
        migrations.AlterField(
            model_name="thirdpartyestimate",
            name="description",
            field=models.CharField(max_length=255, verbose_name="omschrijving"),
        ),
    ]
