# Generated by Django 5.2.10 on 2026-01-21 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0023_alter_thirdpartyestimate_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personchange",
            name="minimum_hourly_tariff",
        ),
    ]
