# Generated by Django 5.2.10 on 2026-01-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0024_remove_personchange_minimum_hourly_tariff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="hours",
            field=models.IntegerField(default=0, verbose_name="uren"),
        ),
        migrations.AlterField(
            model_name="personchange",
            name="hours_per_week",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="uren per week"
            ),
        ),
        migrations.AlterField(
            model_name="personchange",
            name="standard_hourly_tariff",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="standaard uurtarief"
            ),
        ),
        migrations.AlterField(
            model_name="personchange",
            name="target",
            field=models.IntegerField(blank=True, null=True, verbose_name="target"),
        ),
        migrations.AlterField(
            model_name="workassignment",
            name="hourly_tariff",
            field=models.IntegerField(default=0, verbose_name="uurtarief"),
        ),
        migrations.AlterField(
            model_name="workassignment",
            name="hours",
            field=models.IntegerField(default=0, verbose_name="uren"),
        ),
    ]
