# Generated by Django 5.2.10 on 2026-01-21 15:52

from django.db import migrations, models


def set_initial_date(apps, schema_editor):
    Booking = apps.get_model("trs", "Booking")
    for booking in Booking.objects.all():
        booking.date = booking.year_week.first_day
        booking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0025_alter_booking_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='datum'),
        ),
        migrations.RunPython(set_initial_date),
    ]
