# Generated by Django 5.2.10 on 2026-01-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0026_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="datum"
            ),
        ),
    ]
