# Generated by Django 5.2.10 on 2026-01-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0027_alter_booking_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("booked_by", "booked_on", "date"), name="unique_booking_per_day"
            ),
        ),
    ]
