# Generated by Django 5.2.10 on 2026-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0028_remove_booking_unique_booking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateField(verbose_name="factuurdatum"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payed",
            field=models.DateField(blank=True, null=True, verbose_name="betaald op"),
        ),
        migrations.AlterField(
            model_name="payable",
            name="date",
            field=models.DateField(verbose_name="factuurdatum"),
        ),
        migrations.AlterField(
            model_name="payable",
            name="payed",
            field=models.DateField(
                blank=True, null=True, verbose_name="overgemaakt op"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="bid_send_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="offerte verzonden"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="confirmation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="opdrachtbevestiging binnen"
            ),
        ),
        migrations.AlterField(
            model_name="wbsoproject",
            name="end_date",
            field=models.DateField(verbose_name="einddatum"),
        ),
        migrations.AlterField(
            model_name="wbsoproject",
            name="start_date",
            field=models.DateField(verbose_name="startdatum"),
        ),
    ]
