# Generated by Django 5.2.10 on 2026-02-13 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0029_alter_invoice_date_alter_invoice_payed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workassignment",
            options={
                "ordering": ["assigned_to__name"],
                "verbose_name": "toekenning van werk",
                "verbose_name_plural": "toekenningen van werk",
            },
        ),
    ]
