# Generated by Django 5.2.10 on 2026-06-17 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0030_alter_workassignment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="group",
        ),
    ]
