# Generated by Django 3.2.16 on 2024-12-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trs", "0010_auto_20241216_1859"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="startup_meeting_done",
        ),
    ]
