# Generated by Django 3.2.16 on 2024-12-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0011_remove_project_startup_meeting_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_accepted',
        ),
    ]
